langage: 'php'
php:
  - '7.3'
before_install: false
install:
  - composer require friendsofphp/php-cs-fixer --dev
  - composer install
before_script: true
script:
  - phpunit tests
after_script: true
